/* This scripts should normally delete all tables, etc in your account */
BEGIN
 FOR I IN (SELECT DISTINCT NAME FROM USER_SOURCE WHERE type = 'PROCEDURE')
  LOOP
	 EXECUTE IMMEDIATE 'DROP PROCEDURE '||I.NAME;
  END LOOP;

 FOR I IN (SELECT DISTINCT NAME FROM USER_SOURCE WHERE type = 'FUNCTION')
  LOOP
	 EXECUTE IMMEDIATE 'DROP FUNCTION '||I.NAME;
  END LOOP;

 FOR I IN (SELECT DISTINCT TABLE_name FROM user_TABLES)
  LOOP
	 EXECUTE IMMEDIATE 'DROP TABLE '||I.TABLE_NAME || ' CASCADE CONSTRAINTS';
  END LOOP;

 FOR I IN (SELECT DISTINCT SEQUENCE_name FROM user_SEQUENCES)
  LOOP
	EXECUTE IMMEDIATE 'DROP SEQUENCE '||I.SEQUENCE_NAME;
  END LOOP;

 FOR I IN (SELECT TRIGGER_NAME FROM USER_TRIGGERS)
  LOOP
	EXECUTE IMMEDIATE('DROP TRIGGER ' || user || '.' || i.trigger_name);
  END LOOP;
END;
/